### ISSUE TITLE
Translation not on bubble/not fully translated

### ISSUE THREAD

**Issue by rashid19961** [mannu691/TachiyomiSY#1]
### Steps to reproduce

1. Download for ex magic emperor
2. Try to translate using offline option
3. Disabled cbz and used long strip
![Screenshot_20240601_195227_TachiyomiSY](https://github.com/mannu691/TachiyomiSY/assets/18513200/fb67c478-a0f0-4889-bcb9-dee2668048bf)

### Expected behavior

All bubbles should be translated and translation should've be inside bubble

### Actual behavior

Translation outside bubble and not everything translated 

### TachiyomiSY version

1.10.5

### Android version

14 One Ui 6.1

### Device

S24 ultra 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by mannu691** [comment]
I'll look into it , the problem is that there is no consistency in font sizes or resolution,so the grace values i am adding to the font size and coords may not be scaled accordingly
