### ISSUE TITLE
Different apk package name than TachiyomiSY, to use both at the same time.

### ISSUE THREAD

**Issue by kaine-nier** [mannu691/TachiyomiSY#2]
### Describe your suggested feature

Hello, thanks for this great app, it is really helpful.
I already use tachiyomisy but would also like to use this fork to help me learn Chinese and Japanese.
So, I think it would be great if both this apk and the original tachiyomisy could be used together on the same tablet/phone.
But when I try to install it, it would ask if I want to update tachiyomisy, that's why having another package name would solve this problem.
Thanks, have a great day.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by mannu691** [comment]
Alright , i'll change this fork to some other name , any suggestions?
TachuyomiAT maybe
